server:
  port: 2001

spring:
  application:
    name: seata-order-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: wht20020930

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    io:
      seata: info

seata:
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: ""
      group: SEATA_GROUP
      application: seata-server
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
  data-source-proxy-mode: AT

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atg.entity
  configuration:
    map-underscore-to-camel-case: true
