server:
  port: 9001

spring:
  application:
    name: spring-cloud-alibaba-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #group: GROUP_PAYMENT
#      config:
#        server-addr:
#        group: GROUP_PAYMENT

