server:
  port: 8001

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atg.cloud.entity
  configuration:
    map-underscore-to-camel-case: true